### ISSUE TITLE
Stopwords basis

### ISSUE THREAD

**Issue by rishshah** [vikasing/news-stopwords#1]
Hi @vikasing,

I am not sure how are you actually calculating stopwords.  And for what problem are these words actually stopwords?  Words like "surge" and "downbeat" are also in the list, which can predict some sentiment. Can you describe your approach for creating this list?

**Comment by vikasing** [comment]
@rishshah 
In readme file under the section '[structure of files](https://github.com/vikasing/news-stopwords#structure-of-the-files)' there is some explanation on how these terms are ranked. The lists contain the most frequent terms that appeared in the news articles. 

Many words are verbs, adjectives, etc. as you go down the list, these terms can certainly help in predicting the sentiment when looking at the individual article/text, so you should not omit them. If your aim is to predict the sentiment then you should avoid this list or can assign a relevance score to each term. The list helps in IR related tasks, like calculating the importance of a news article.
